package ifql

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// DO NOT EDIT: This file is auto generated by the pigeon PEG parser generator.

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 8, col: 1, offset: 100},
			expr: &actionExpr{
				pos: position{line: 9, col: 5, offset: 110},
				run: (*parser).callonStart1,
				expr: &seqExpr{
					pos: position{line: 9, col: 5, offset: 110},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 9, col: 5, offset: 110},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 9, col: 8, offset: 113},
							label: "program",
							expr: &ruleRefExpr{
								pos:  position{line: 9, col: 16, offset: 121},
								name: "Program",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 9, col: 24, offset: 129},
							name: "__",
						},
						&ruleRefExpr{
							pos:  position{line: 9, col: 27, offset: 132},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Program",
			pos:  position{line: 13, col: 1, offset: 171},
			expr: &actionExpr{
				pos: position{line: 14, col: 5, offset: 183},
				run: (*parser).callonProgram1,
				expr: &labeledExpr{
					pos:   position{line: 14, col: 5, offset: 183},
					label: "body",
					expr: &ruleRefExpr{
						pos:  position{line: 14, col: 10, offset: 188},
						name: "SourceElements",
					},
				},
			},
		},
		{
			name: "SourceElements",
			pos:  position{line: 18, col: 1, offset: 254},
			expr: &actionExpr{
				pos: position{line: 19, col: 5, offset: 273},
				run: (*parser).callonSourceElements1,
				expr: &seqExpr{
					pos: position{line: 19, col: 5, offset: 273},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 19, col: 5, offset: 273},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 19, col: 10, offset: 278},
								name: "SourceElement",
							},
						},
						&labeledExpr{
							pos:   position{line: 19, col: 24, offset: 292},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 19, col: 29, offset: 297},
								expr: &seqExpr{
									pos: position{line: 19, col: 30, offset: 298},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 19, col: 30, offset: 298},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 19, col: 33, offset: 301},
											name: "SourceElement",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SourceElement",
			pos:  position{line: 23, col: 1, offset: 360},
			expr: &ruleRefExpr{
				pos:  position{line: 24, col: 5, offset: 378},
				name: "Statement",
			},
		},
		{
			name: "Statement",
			pos:  position{line: 26, col: 1, offset: 389},
			expr: &choiceExpr{
				pos: position{line: 27, col: 5, offset: 403},
				alternatives: []interface{}{
					&labeledExpr{
						pos:   position{line: 27, col: 5, offset: 403},
						label: "varstmt",
						expr: &ruleRefExpr{
							pos:  position{line: 27, col: 13, offset: 411},
							name: "VariableStatement",
						},
					},
					&labeledExpr{
						pos:   position{line: 28, col: 5, offset: 433},
						label: "exprstmt",
						expr: &ruleRefExpr{
							pos:  position{line: 28, col: 14, offset: 442},
							name: "ExpressionStatement",
						},
					},
				},
			},
		},
		{
			name: "VariableStatement",
			pos:  position{line: 30, col: 1, offset: 463},
			expr: &actionExpr{
				pos: position{line: 31, col: 5, offset: 485},
				run: (*parser).callonVariableStatement1,
				expr: &seqExpr{
					pos: position{line: 31, col: 5, offset: 485},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 31, col: 5, offset: 485},
							name: "VarToken",
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 14, offset: 494},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 31, col: 17, offset: 497},
							label: "declaration",
							expr: &ruleRefExpr{
								pos:  position{line: 31, col: 29, offset: 509},
								name: "VariableDeclaration",
							},
						},
					},
				},
			},
		},
		{
			name: "VarToken",
			pos:  position{line: 35, col: 1, offset: 587},
			expr: &litMatcher{
				pos:        position{line: 35, col: 12, offset: 598},
				val:        "var",
				ignoreCase: false,
			},
		},
		{
			name: "VariableDeclaration",
			pos:  position{line: 37, col: 1, offset: 605},
			expr: &actionExpr{
				pos: position{line: 38, col: 5, offset: 629},
				run: (*parser).callonVariableDeclaration1,
				expr: &seqExpr{
					pos: position{line: 38, col: 5, offset: 629},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 38, col: 5, offset: 629},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 8, offset: 632},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 38, col: 19, offset: 643},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 22, offset: 646},
							label: "initExpr",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 31, offset: 655},
								name: "Initializer",
							},
						},
					},
				},
			},
		},
		{
			name: "Initializer",
			pos:  position{line: 42, col: 1, offset: 726},
			expr: &actionExpr{
				pos: position{line: 43, col: 5, offset: 742},
				run: (*parser).callonInitializer1,
				expr: &seqExpr{
					pos: position{line: 43, col: 5, offset: 742},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 43, col: 5, offset: 742},
							val:        "=",
							ignoreCase: false,
						},
						&notExpr{
							pos: position{line: 43, col: 9, offset: 746},
							expr: &litMatcher{
								pos:        position{line: 43, col: 10, offset: 747},
								val:        "=",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 43, col: 14, offset: 751},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 43, col: 17, offset: 754},
							label: "expression",
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 28, offset: 765},
								name: "VariableExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "VariableExpression",
			pos:  position{line: 48, col: 1, offset: 892},
			expr: &choiceExpr{
				pos: position{line: 49, col: 5, offset: 915},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 49, col: 5, offset: 915},
						name: "CallExpression",
					},
					&ruleRefExpr{
						pos:  position{line: 50, col: 5, offset: 934},
						name: "Primary",
					},
				},
			},
		},
		{
			name: "ExpressionStatement",
			pos:  position{line: 52, col: 1, offset: 943},
			expr: &actionExpr{
				pos: position{line: 53, col: 5, offset: 967},
				run: (*parser).callonExpressionStatement1,
				expr: &labeledExpr{
					pos:   position{line: 53, col: 5, offset: 967},
					label: "call",
					expr: &ruleRefExpr{
						pos:  position{line: 53, col: 10, offset: 972},
						name: "CallExpression",
					},
				},
			},
		},
		{
			name: "MemberExpression",
			pos:  position{line: 57, col: 1, offset: 1041},
			expr: &actionExpr{
				pos: position{line: 58, col: 5, offset: 1062},
				run: (*parser).callonMemberExpression1,
				expr: &seqExpr{
					pos: position{line: 58, col: 5, offset: 1062},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 58, col: 5, offset: 1062},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 58, col: 10, offset: 1067},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 59, col: 5, offset: 1109},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 59, col: 10, offset: 1114},
								expr: &actionExpr{
									pos: position{line: 60, col: 9, offset: 1124},
									run: (*parser).callonMemberExpression7,
									expr: &seqExpr{
										pos: position{line: 60, col: 9, offset: 1124},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 60, col: 9, offset: 1124},
												name: "__",
											},
											&litMatcher{
												pos:        position{line: 60, col: 12, offset: 1127},
												val:        ".",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 60, col: 16, offset: 1131},
												name: "__",
											},
											&labeledExpr{
												pos:   position{line: 60, col: 19, offset: 1134},
												label: "property",
												expr: &ruleRefExpr{
													pos:  position{line: 60, col: 28, offset: 1143},
													name: "Identifier",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CallExpression",
			pos:  position{line: 68, col: 1, offset: 1269},
			expr: &actionExpr{
				pos: position{line: 69, col: 5, offset: 1288},
				run: (*parser).callonCallExpression1,
				expr: &seqExpr{
					pos: position{line: 69, col: 5, offset: 1288},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 69, col: 5, offset: 1288},
							label: "head",
							expr: &actionExpr{
								pos: position{line: 70, col: 7, offset: 1301},
								run: (*parser).callonCallExpression4,
								expr: &seqExpr{
									pos: position{line: 70, col: 7, offset: 1301},
									exprs: []interface{}{
										&labeledExpr{
											pos:   position{line: 70, col: 7, offset: 1301},
											label: "callee",
											expr: &ruleRefExpr{
												pos:  position{line: 70, col: 14, offset: 1308},
												name: "MemberExpression",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 70, col: 31, offset: 1325},
											name: "__",
										},
										&labeledExpr{
											pos:   position{line: 70, col: 34, offset: 1328},
											label: "args",
											expr: &ruleRefExpr{
												pos:  position{line: 70, col: 39, offset: 1333},
												name: "Arguments",
											},
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 74, col: 5, offset: 1416},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 74, col: 10, offset: 1421},
								expr: &choiceExpr{
									pos: position{line: 75, col: 9, offset: 1431},
									alternatives: []interface{}{
										&actionExpr{
											pos: position{line: 75, col: 9, offset: 1431},
											run: (*parser).callonCallExpression14,
											expr: &seqExpr{
												pos: position{line: 75, col: 9, offset: 1431},
												exprs: []interface{}{
													&ruleRefExpr{
														pos:  position{line: 75, col: 9, offset: 1431},
														name: "__",
													},
													&labeledExpr{
														pos:   position{line: 75, col: 12, offset: 1434},
														label: "args",
														expr: &ruleRefExpr{
															pos:  position{line: 75, col: 17, offset: 1439},
															name: "Arguments",
														},
													},
												},
											},
										},
										&actionExpr{
											pos: position{line: 78, col: 9, offset: 1521},
											run: (*parser).callonCallExpression19,
											expr: &seqExpr{
												pos: position{line: 78, col: 9, offset: 1521},
												exprs: []interface{}{
													&ruleRefExpr{
														pos:  position{line: 78, col: 9, offset: 1521},
														name: "__",
													},
													&litMatcher{
														pos:        position{line: 78, col: 12, offset: 1524},
														val:        ".",
														ignoreCase: false,
													},
													&ruleRefExpr{
														pos:  position{line: 78, col: 16, offset: 1528},
														name: "__",
													},
													&labeledExpr{
														pos:   position{line: 78, col: 19, offset: 1531},
														label: "property",
														expr: &ruleRefExpr{
															pos:  position{line: 78, col: 28, offset: 1540},
															name: "Identifier",
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Arguments",
			pos:  position{line: 86, col: 1, offset: 1691},
			expr: &actionExpr{
				pos: position{line: 87, col: 5, offset: 1705},
				run: (*parser).callonArguments1,
				expr: &seqExpr{
					pos: position{line: 87, col: 5, offset: 1705},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 87, col: 5, offset: 1705},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 9, offset: 1709},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 87, col: 12, offset: 1712},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 87, col: 17, offset: 1717},
								expr: &ruleRefExpr{
									pos:  position{line: 87, col: 18, offset: 1718},
									name: "FunctionArgs",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 33, offset: 1733},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 87, col: 36, offset: 1736},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FunctionArgs",
			pos:  position{line: 91, col: 1, offset: 1772},
			expr: &actionExpr{
				pos: position{line: 92, col: 5, offset: 1789},
				run: (*parser).callonFunctionArgs1,
				expr: &seqExpr{
					pos: position{line: 92, col: 5, offset: 1789},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 92, col: 5, offset: 1789},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 11, offset: 1795},
								name: "FunctionArg",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 23, offset: 1807},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 26, offset: 1810},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 92, col: 31, offset: 1815},
								expr: &ruleRefExpr{
									pos:  position{line: 92, col: 31, offset: 1815},
									name: "FunctionArgsRest",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionArgsRest",
			pos:  position{line: 96, col: 1, offset: 1890},
			expr: &actionExpr{
				pos: position{line: 97, col: 5, offset: 1911},
				run: (*parser).callonFunctionArgsRest1,
				expr: &seqExpr{
					pos: position{line: 97, col: 5, offset: 1911},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 97, col: 5, offset: 1911},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 9, offset: 1915},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 13, offset: 1919},
							label: "arg",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 17, offset: 1923},
								name: "FunctionArg",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionArg",
			pos:  position{line: 101, col: 1, offset: 1966},
			expr: &actionExpr{
				pos: position{line: 102, col: 5, offset: 1982},
				run: (*parser).callonFunctionArg1,
				expr: &seqExpr{
					pos: position{line: 102, col: 5, offset: 1982},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 102, col: 5, offset: 1982},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 102, col: 9, offset: 1986},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 102, col: 20, offset: 1997},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 102, col: 24, offset: 2001},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 102, col: 28, offset: 2005},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 102, col: 31, offset: 2008},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 102, col: 37, offset: 2014},
								name: "FunctionArgValues",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionArgValues",
			pos:  position{line: 106, col: 1, offset: 2090},
			expr: &choiceExpr{
				pos: position{line: 107, col: 5, offset: 2112},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 107, col: 5, offset: 2112},
						name: "LambdaExpression",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 5, offset: 2133},
						name: "Primary",
					},
				},
			},
		},
		{
			name: "LambdaExpression",
			pos:  position{line: 110, col: 1, offset: 2142},
			expr: &actionExpr{
				pos: position{line: 111, col: 5, offset: 2163},
				run: (*parser).callonLambdaExpression1,
				expr: &seqExpr{
					pos: position{line: 111, col: 5, offset: 2163},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 111, col: 5, offset: 2163},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 9, offset: 2167},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 111, col: 12, offset: 2170},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 17, offset: 2175},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 22, offset: 2180},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 111, col: 26, offset: 2184},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 122, col: 1, offset: 2417},
			expr: &ruleRefExpr{
				pos:  position{line: 123, col: 5, offset: 2426},
				name: "Logical",
			},
		},
		{
			name: "LogicalOperators",
			pos:  position{line: 125, col: 1, offset: 2435},
			expr: &actionExpr{
				pos: position{line: 126, col: 5, offset: 2456},
				run: (*parser).callonLogicalOperators1,
				expr: &choiceExpr{
					pos: position{line: 126, col: 6, offset: 2457},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 126, col: 6, offset: 2457},
							val:        "or",
							ignoreCase: true,
						},
						&litMatcher{
							pos:        position{line: 126, col: 14, offset: 2465},
							val:        "and",
							ignoreCase: true,
						},
					},
				},
			},
		},
		{
			name: "Logical",
			pos:  position{line: 130, col: 1, offset: 2517},
			expr: &actionExpr{
				pos: position{line: 131, col: 5, offset: 2529},
				run: (*parser).callonLogical1,
				expr: &seqExpr{
					pos: position{line: 131, col: 5, offset: 2529},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 131, col: 5, offset: 2529},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 10, offset: 2534},
								name: "Equality",
							},
						},
						&labeledExpr{
							pos:   position{line: 131, col: 19, offset: 2543},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 131, col: 24, offset: 2548},
								expr: &seqExpr{
									pos: position{line: 131, col: 26, offset: 2550},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 131, col: 26, offset: 2550},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 30, offset: 2554},
											name: "LogicalOperators",
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 47, offset: 2571},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 51, offset: 2575},
											name: "Equality",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EqualityOperators",
			pos:  position{line: 135, col: 1, offset: 2654},
			expr: &actionExpr{
				pos: position{line: 136, col: 5, offset: 2676},
				run: (*parser).callonEqualityOperators1,
				expr: &choiceExpr{
					pos: position{line: 136, col: 6, offset: 2677},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 136, col: 6, offset: 2677},
							val:        "==",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 136, col: 13, offset: 2684},
							val:        "!=",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Equality",
			pos:  position{line: 140, col: 1, offset: 2730},
			expr: &actionExpr{
				pos: position{line: 141, col: 5, offset: 2743},
				run: (*parser).callonEquality1,
				expr: &seqExpr{
					pos: position{line: 141, col: 5, offset: 2743},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 141, col: 5, offset: 2743},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 10, offset: 2748},
								name: "Relational",
							},
						},
						&labeledExpr{
							pos:   position{line: 141, col: 21, offset: 2759},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 141, col: 26, offset: 2764},
								expr: &seqExpr{
									pos: position{line: 141, col: 28, offset: 2766},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 141, col: 28, offset: 2766},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 141, col: 31, offset: 2769},
											name: "EqualityOperators",
										},
										&ruleRefExpr{
											pos:  position{line: 141, col: 49, offset: 2787},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 141, col: 52, offset: 2790},
											name: "Relational",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RelationalOperators",
			pos:  position{line: 145, col: 1, offset: 2870},
			expr: &actionExpr{
				pos: position{line: 146, col: 5, offset: 2894},
				run: (*parser).callonRelationalOperators1,
				expr: &choiceExpr{
					pos: position{line: 146, col: 9, offset: 2898},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 146, col: 9, offset: 2898},
							val:        "<=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 147, col: 9, offset: 2911},
							val:        "<",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 148, col: 9, offset: 2923},
							val:        ">=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 149, col: 9, offset: 2936},
							val:        ">",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 150, col: 9, offset: 2948},
							val:        "startswith",
							ignoreCase: true,
						},
						&litMatcher{
							pos:        position{line: 151, col: 9, offset: 2970},
							val:        "in",
							ignoreCase: true,
						},
						&litMatcher{
							pos:        position{line: 152, col: 9, offset: 2984},
							val:        "not empty",
							ignoreCase: true,
						},
						&litMatcher{
							pos:        position{line: 153, col: 9, offset: 3005},
							val:        "empty",
							ignoreCase: true,
						},
					},
				},
			},
		},
		{
			name: "Relational",
			pos:  position{line: 158, col: 1, offset: 3063},
			expr: &actionExpr{
				pos: position{line: 159, col: 5, offset: 3078},
				run: (*parser).callonRelational1,
				expr: &seqExpr{
					pos: position{line: 159, col: 5, offset: 3078},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 159, col: 5, offset: 3078},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 10, offset: 3083},
								name: "Additive",
							},
						},
						&labeledExpr{
							pos:   position{line: 159, col: 19, offset: 3092},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 159, col: 24, offset: 3097},
								expr: &seqExpr{
									pos: position{line: 159, col: 26, offset: 3099},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 159, col: 26, offset: 3099},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 159, col: 29, offset: 3102},
											name: "RelationalOperators",
										},
										&ruleRefExpr{
											pos:  position{line: 159, col: 49, offset: 3122},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 159, col: 52, offset: 3125},
											name: "Additive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AdditiveOperator",
			pos:  position{line: 163, col: 1, offset: 3203},
			expr: &actionExpr{
				pos: position{line: 164, col: 5, offset: 3224},
				run: (*parser).callonAdditiveOperator1,
				expr: &choiceExpr{
					pos: position{line: 164, col: 6, offset: 3225},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 164, col: 6, offset: 3225},
							val:        "+",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 164, col: 12, offset: 3231},
							val:        "-",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 168, col: 1, offset: 3279},
			expr: &actionExpr{
				pos: position{line: 169, col: 5, offset: 3292},
				run: (*parser).callonAdditive1,
				expr: &seqExpr{
					pos: position{line: 169, col: 5, offset: 3292},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 169, col: 5, offset: 3292},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 169, col: 10, offset: 3297},
								name: "Multiplicative",
							},
						},
						&labeledExpr{
							pos:   position{line: 169, col: 25, offset: 3312},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 169, col: 30, offset: 3317},
								expr: &seqExpr{
									pos: position{line: 169, col: 32, offset: 3319},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 169, col: 32, offset: 3319},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 169, col: 35, offset: 3322},
											name: "AdditiveOperator",
										},
										&ruleRefExpr{
											pos:  position{line: 169, col: 52, offset: 3339},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 169, col: 55, offset: 3342},
											name: "Multiplicative",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MultiplicativeOperator",
			pos:  position{line: 173, col: 1, offset: 3426},
			expr: &actionExpr{
				pos: position{line: 174, col: 5, offset: 3453},
				run: (*parser).callonMultiplicativeOperator1,
				expr: &choiceExpr{
					pos: position{line: 174, col: 6, offset: 3454},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 174, col: 6, offset: 3454},
							val:        "*",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 174, col: 12, offset: 3460},
							val:        "/",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 178, col: 1, offset: 3504},
			expr: &actionExpr{
				pos: position{line: 179, col: 5, offset: 3523},
				run: (*parser).callonMultiplicative1,
				expr: &seqExpr{
					pos: position{line: 179, col: 5, offset: 3523},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 179, col: 5, offset: 3523},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 179, col: 10, offset: 3528},
								name: "Primary",
							},
						},
						&labeledExpr{
							pos:   position{line: 179, col: 18, offset: 3536},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 179, col: 23, offset: 3541},
								expr: &seqExpr{
									pos: position{line: 179, col: 25, offset: 3543},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 179, col: 25, offset: 3543},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 179, col: 28, offset: 3546},
											name: "MultiplicativeOperator",
										},
										&ruleRefExpr{
											pos:  position{line: 179, col: 51, offset: 3569},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 179, col: 54, offset: 3572},
											name: "Primary",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Primary",
			pos:  position{line: 183, col: 1, offset: 3649},
			expr: &choiceExpr{
				pos: position{line: 184, col: 5, offset: 3661},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 184, col: 5, offset: 3661},
						run: (*parser).callonPrimary2,
						expr: &seqExpr{
							pos: position{line: 184, col: 5, offset: 3661},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 184, col: 5, offset: 3661},
									val:        "(",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 184, col: 9, offset: 3665},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 184, col: 12, offset: 3668},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 184, col: 17, offset: 3673},
										name: "Logical",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 184, col: 25, offset: 3681},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 184, col: 28, offset: 3684},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 187, col: 5, offset: 3723},
						name: "Array",
					},
					&ruleRefExpr{
						pos:  position{line: 188, col: 5, offset: 3733},
						name: "StringLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 189, col: 5, offset: 3751},
						name: "BooleanLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 5, offset: 3770},
						name: "RegularExpressionLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 5, offset: 3799},
						name: "Duration",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 5, offset: 3812},
						name: "DateTime",
					},
					&ruleRefExpr{
						pos:  position{line: 193, col: 5, offset: 3825},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 194, col: 5, offset: 3836},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 195, col: 5, offset: 3848},
						name: "Field",
					},
					&ruleRefExpr{
						pos:  position{line: 196, col: 5, offset: 3858},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 199, col: 1, offset: 3871},
			expr: &actionExpr{
				pos: position{line: 200, col: 5, offset: 3881},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 200, col: 5, offset: 3881},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 200, col: 5, offset: 3881},
							val:        "[",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 200, col: 9, offset: 3885},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 200, col: 12, offset: 3888},
							label: "elements",
							expr: &zeroOrOneExpr{
								pos: position{line: 200, col: 21, offset: 3897},
								expr: &ruleRefExpr{
									pos:  position{line: 200, col: 21, offset: 3897},
									name: "ArrayElements",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 200, col: 36, offset: 3912},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 200, col: 39, offset: 3915},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ArrayElements",
			pos:  position{line: 204, col: 1, offset: 3955},
			expr: &actionExpr{
				pos: position{line: 205, col: 5, offset: 3973},
				run: (*parser).callonArrayElements1,
				expr: &seqExpr{
					pos: position{line: 205, col: 5, offset: 3973},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 205, col: 5, offset: 3973},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 205, col: 11, offset: 3979},
								name: "Primary",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 205, col: 19, offset: 3987},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 205, col: 22, offset: 3990},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 205, col: 27, offset: 3995},
								expr: &ruleRefExpr{
									pos:  position{line: 205, col: 27, offset: 3995},
									name: "ArrayRest",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ArrayRest",
			pos:  position{line: 209, col: 1, offset: 4067},
			expr: &actionExpr{
				pos: position{line: 210, col: 5, offset: 4081},
				run: (*parser).callonArrayRest1,
				expr: &seqExpr{
					pos: position{line: 210, col: 5, offset: 4081},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 210, col: 5, offset: 4081},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 210, col: 9, offset: 4085},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 210, col: 12, offset: 4088},
							label: "element",
							expr: &ruleRefExpr{
								pos:  position{line: 210, col: 20, offset: 4096},
								name: "Primary",
							},
						},
					},
				},
			},
		},
		{
			name: "DateFullYear",
			pos:  position{line: 214, col: 1, offset: 4139},
			expr: &seqExpr{
				pos: position{line: 215, col: 5, offset: 4156},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 215, col: 5, offset: 4156},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 215, col: 11, offset: 4162},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 215, col: 17, offset: 4168},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 215, col: 23, offset: 4174},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "DateMonth",
			pos:  position{line: 217, col: 1, offset: 4181},
			expr: &seqExpr{
				pos: position{line: 219, col: 5, offset: 4206},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 219, col: 5, offset: 4206},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 219, col: 11, offset: 4212},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "DateMDay",
			pos:  position{line: 221, col: 1, offset: 4219},
			expr: &seqExpr{
				pos: position{line: 224, col: 5, offset: 4289},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 224, col: 5, offset: 4289},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 224, col: 11, offset: 4295},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "TimeHour",
			pos:  position{line: 226, col: 1, offset: 4302},
			expr: &seqExpr{
				pos: position{line: 228, col: 5, offset: 4326},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 228, col: 5, offset: 4326},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 228, col: 11, offset: 4332},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "TimeMinute",
			pos:  position{line: 230, col: 1, offset: 4339},
			expr: &seqExpr{
				pos: position{line: 232, col: 5, offset: 4365},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 232, col: 5, offset: 4365},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 232, col: 11, offset: 4371},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "TimeSecond",
			pos:  position{line: 234, col: 1, offset: 4378},
			expr: &seqExpr{
				pos: position{line: 237, col: 5, offset: 4450},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 237, col: 5, offset: 4450},
						name: "Digit",
					},
					&ruleRefExpr{
						pos:  position{line: 237, col: 11, offset: 4456},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "TimeSecFrac",
			pos:  position{line: 239, col: 1, offset: 4463},
			expr: &seqExpr{
				pos: position{line: 240, col: 5, offset: 4479},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 240, col: 5, offset: 4479},
						val:        ".",
						ignoreCase: false,
					},
					&oneOrMoreExpr{
						pos: position{line: 240, col: 9, offset: 4483},
						expr: &ruleRefExpr{
							pos:  position{line: 240, col: 9, offset: 4483},
							name: "Digit",
						},
					},
				},
			},
		},
		{
			name: "TimeNumOffset",
			pos:  position{line: 242, col: 1, offset: 4491},
			expr: &seqExpr{
				pos: position{line: 243, col: 5, offset: 4509},
				exprs: []interface{}{
					&choiceExpr{
						pos: position{line: 243, col: 6, offset: 4510},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 243, col: 6, offset: 4510},
								val:        "+",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 243, col: 12, offset: 4516},
								val:        "-",
								ignoreCase: false,
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 243, col: 17, offset: 4521},
						name: "TimeHour",
					},
					&litMatcher{
						pos:        position{line: 243, col: 26, offset: 4530},
						val:        ":",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 243, col: 30, offset: 4534},
						name: "TimeMinute",
					},
				},
			},
		},
		{
			name: "TimeOffset",
			pos:  position{line: 245, col: 1, offset: 4546},
			expr: &choiceExpr{
				pos: position{line: 246, col: 6, offset: 4562},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 246, col: 6, offset: 4562},
						val:        "Z",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 246, col: 12, offset: 4568},
						name: "TimeNumOffset",
					},
				},
			},
		},
		{
			name: "PartialTime",
			pos:  position{line: 248, col: 1, offset: 4584},
			expr: &seqExpr{
				pos: position{line: 249, col: 5, offset: 4600},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 249, col: 5, offset: 4600},
						name: "TimeHour",
					},
					&litMatcher{
						pos:        position{line: 249, col: 14, offset: 4609},
						val:        ":",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 249, col: 18, offset: 4613},
						name: "TimeMinute",
					},
					&litMatcher{
						pos:        position{line: 249, col: 29, offset: 4624},
						val:        ":",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 249, col: 33, offset: 4628},
						name: "TimeSecond",
					},
					&zeroOrOneExpr{
						pos: position{line: 249, col: 44, offset: 4639},
						expr: &ruleRefExpr{
							pos:  position{line: 249, col: 44, offset: 4639},
							name: "TimeSecFrac",
						},
					},
				},
			},
		},
		{
			name: "FullDate",
			pos:  position{line: 251, col: 1, offset: 4653},
			expr: &seqExpr{
				pos: position{line: 252, col: 5, offset: 4666},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 252, col: 5, offset: 4666},
						name: "DateFullYear",
					},
					&litMatcher{
						pos:        position{line: 252, col: 18, offset: 4679},
						val:        "-",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 252, col: 22, offset: 4683},
						name: "DateMonth",
					},
					&litMatcher{
						pos:        position{line: 252, col: 32, offset: 4693},
						val:        "-",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 252, col: 36, offset: 4697},
						name: "DateMDay",
					},
				},
			},
		},
		{
			name: "FullTime",
			pos:  position{line: 254, col: 1, offset: 4707},
			expr: &seqExpr{
				pos: position{line: 255, col: 5, offset: 4720},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 255, col: 5, offset: 4720},
						name: "PartialTime",
					},
					&ruleRefExpr{
						pos:  position{line: 255, col: 17, offset: 4732},
						name: "TimeOffset",
					},
				},
			},
		},
		{
			name: "DateTime",
			pos:  position{line: 257, col: 1, offset: 4744},
			expr: &actionExpr{
				pos: position{line: 258, col: 5, offset: 4757},
				run: (*parser).callonDateTime1,
				expr: &seqExpr{
					pos: position{line: 258, col: 5, offset: 4757},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 258, col: 5, offset: 4757},
							name: "FullDate",
						},
						&litMatcher{
							pos:        position{line: 258, col: 14, offset: 4766},
							val:        "T",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 258, col: 18, offset: 4770},
							name: "FullTime",
						},
					},
				},
			},
		},
		{
			name: "NanoSecondUnits",
			pos:  position{line: 262, col: 1, offset: 4825},
			expr: &litMatcher{
				pos:        position{line: 263, col: 5, offset: 4845},
				val:        "ns",
				ignoreCase: false,
			},
		},
		{
			name: "MicroSecondUnits",
			pos:  position{line: 265, col: 1, offset: 4851},
			expr: &choiceExpr{
				pos: position{line: 266, col: 6, offset: 4873},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 266, col: 6, offset: 4873},
						val:        "us",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 266, col: 13, offset: 4880},
						val:        "µs",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 266, col: 20, offset: 4888},
						val:        "μs",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MilliSecondUnits",
			pos:  position{line: 268, col: 1, offset: 4896},
			expr: &litMatcher{
				pos:        position{line: 269, col: 5, offset: 4917},
				val:        "ms",
				ignoreCase: false,
			},
		},
		{
			name: "SecondUnits",
			pos:  position{line: 271, col: 1, offset: 4923},
			expr: &litMatcher{
				pos:        position{line: 272, col: 5, offset: 4939},
				val:        "s",
				ignoreCase: false,
			},
		},
		{
			name: "MinuteUnits",
			pos:  position{line: 274, col: 1, offset: 4944},
			expr: &litMatcher{
				pos:        position{line: 275, col: 5, offset: 4960},
				val:        "m",
				ignoreCase: false,
			},
		},
		{
			name: "HourUnits",
			pos:  position{line: 277, col: 1, offset: 4965},
			expr: &litMatcher{
				pos:        position{line: 278, col: 5, offset: 4979},
				val:        "h",
				ignoreCase: false,
			},
		},
		{
			name: "DurationUnits",
			pos:  position{line: 280, col: 1, offset: 4984},
			expr: &choiceExpr{
				pos: position{line: 282, col: 9, offset: 5012},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 282, col: 9, offset: 5012},
						name: "NanoSecondUnits",
					},
					&ruleRefExpr{
						pos:  position{line: 283, col: 9, offset: 5036},
						name: "MicroSecondUnits",
					},
					&ruleRefExpr{
						pos:  position{line: 284, col: 9, offset: 5061},
						name: "MilliSecondUnits",
					},
					&ruleRefExpr{
						pos:  position{line: 285, col: 9, offset: 5086},
						name: "SecondUnits",
					},
					&ruleRefExpr{
						pos:  position{line: 286, col: 9, offset: 5106},
						name: "MinuteUnits",
					},
					&ruleRefExpr{
						pos:  position{line: 287, col: 9, offset: 5126},
						name: "HourUnits",
					},
				},
			},
		},
		{
			name: "SingleDuration",
			pos:  position{line: 290, col: 1, offset: 5143},
			expr: &seqExpr{
				pos: position{line: 291, col: 5, offset: 5162},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 291, col: 5, offset: 5162},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 291, col: 13, offset: 5170},
						name: "DurationUnits",
					},
				},
			},
		},
		{
			name: "Duration",
			pos:  position{line: 293, col: 1, offset: 5185},
			expr: &actionExpr{
				pos: position{line: 294, col: 5, offset: 5198},
				run: (*parser).callonDuration1,
				expr: &oneOrMoreExpr{
					pos: position{line: 294, col: 5, offset: 5198},
					expr: &ruleRefExpr{
						pos:  position{line: 294, col: 5, offset: 5198},
						name: "SingleDuration",
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 298, col: 1, offset: 5267},
			expr: &choiceExpr{
				pos: position{line: 299, col: 5, offset: 5285},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 299, col: 5, offset: 5285},
						run: (*parser).callonStringLiteral2,
						expr: &seqExpr{
							pos: position{line: 299, col: 7, offset: 5287},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 299, col: 7, offset: 5287},
									val:        "\"",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 299, col: 11, offset: 5291},
									expr: &ruleRefExpr{
										pos:  position{line: 299, col: 11, offset: 5291},
										name: "DoubleStringChar",
									},
								},
								&litMatcher{
									pos:        position{line: 299, col: 29, offset: 5309},
									val:        "\"",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 302, col: 5, offset: 5373},
						run: (*parser).callonStringLiteral8,
						expr: &seqExpr{
							pos: position{line: 302, col: 7, offset: 5375},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 302, col: 7, offset: 5375},
									val:        "\"",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 302, col: 11, offset: 5379},
									expr: &ruleRefExpr{
										pos:  position{line: 302, col: 11, offset: 5379},
										name: "DoubleStringChar",
									},
								},
								&choiceExpr{
									pos: position{line: 302, col: 31, offset: 5399},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 302, col: 31, offset: 5399},
											name: "EOL",
										},
										&ruleRefExpr{
											pos:  position{line: 302, col: 37, offset: 5405},
											name: "EOF",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 306, col: 1, offset: 5487},
			expr: &choiceExpr{
				pos: position{line: 307, col: 5, offset: 5508},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 307, col: 5, offset: 5508},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 307, col: 5, offset: 5508},
								expr: &choiceExpr{
									pos: position{line: 307, col: 8, offset: 5511},
									alternatives: []interface{}{
										&litMatcher{
											pos:        position{line: 307, col: 8, offset: 5511},
											val:        "\"",
											ignoreCase: false,
										},
										&litMatcher{
											pos:        position{line: 307, col: 14, offset: 5517},
											val:        "\\",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 307, col: 21, offset: 5524},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 307, col: 27, offset: 5530},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 308, col: 5, offset: 5545},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 308, col: 5, offset: 5545},
								val:        "\\",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 308, col: 10, offset: 5550},
								name: "DoubleStringEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleStringEscape",
			pos:  position{line: 310, col: 1, offset: 5570},
			expr: &choiceExpr{
				pos: position{line: 311, col: 5, offset: 5593},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 311, col: 5, offset: 5593},
						val:        "\"",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 312, col: 5, offset: 5601},
						run: (*parser).callonDoubleStringEscape3,
						expr: &choiceExpr{
							pos: position{line: 312, col: 7, offset: 5603},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 312, col: 7, offset: 5603},
									name: "SourceChar",
								},
								&ruleRefExpr{
									pos:  position{line: 312, col: 20, offset: 5616},
									name: "EOL",
								},
								&ruleRefExpr{
									pos:  position{line: 312, col: 26, offset: 5622},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BooleanLiteral",
			pos:  position{line: 316, col: 1, offset: 5694},
			expr: &choiceExpr{
				pos: position{line: 317, col: 5, offset: 5713},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 317, col: 5, offset: 5713},
						run: (*parser).callonBooleanLiteral2,
						expr: &seqExpr{
							pos: position{line: 317, col: 5, offset: 5713},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 317, col: 5, offset: 5713},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 317, col: 8, offset: 5716},
									val:        "true",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 317, col: 15, offset: 5723},
									name: "__",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 320, col: 5, offset: 5787},
						run: (*parser).callonBooleanLiteral7,
						expr: &seqExpr{
							pos: position{line: 320, col: 5, offset: 5787},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 320, col: 5, offset: 5787},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 320, col: 8, offset: 5790},
									val:        "false",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 320, col: 16, offset: 5798},
									name: "__",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 324, col: 1, offset: 5860},
			expr: &actionExpr{
				pos: position{line: 326, col: 5, offset: 5905},
				run: (*parser).callonIdentifier1,
				expr: &oneOrMoreExpr{
					pos: position{line: 326, col: 5, offset: 5905},
					expr: &charClassMatcher{
						pos:        position{line: 326, col: 5, offset: 5905},
						val:        "[\\pL]",
						classes:    []*unicode.RangeTable{rangeTable("L")},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 330, col: 1, offset: 5960},
			expr: &actionExpr{
				pos: position{line: 331, col: 5, offset: 5971},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 331, col: 5, offset: 5971},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 331, col: 5, offset: 5971},
							name: "Integer",
						},
						&litMatcher{
							pos:        position{line: 331, col: 13, offset: 5979},
							val:        ".",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 331, col: 17, offset: 5983},
							expr: &ruleRefExpr{
								pos:  position{line: 331, col: 17, offset: 5983},
								name: "Digit",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 335, col: 1, offset: 6040},
			expr: &actionExpr{
				pos: position{line: 336, col: 5, offset: 6052},
				run: (*parser).callonInteger1,
				expr: &choiceExpr{
					pos: position{line: 336, col: 6, offset: 6053},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 336, col: 6, offset: 6053},
							val:        "0",
							ignoreCase: false,
						},
						&seqExpr{
							pos: position{line: 336, col: 12, offset: 6059},
							exprs: []interface{}{
								&zeroOrOneExpr{
									pos: position{line: 336, col: 12, offset: 6059},
									expr: &litMatcher{
										pos:        position{line: 336, col: 12, offset: 6059},
										val:        "-",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 336, col: 17, offset: 6064},
									name: "NonZeroDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 336, col: 30, offset: 6077},
									expr: &ruleRefExpr{
										pos:  position{line: 336, col: 30, offset: 6077},
										name: "Digit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NonZeroDigit",
			pos:  position{line: 341, col: 1, offset: 6137},
			expr: &charClassMatcher{
				pos:        position{line: 342, col: 5, offset: 6154},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Digit",
			pos:  position{line: 344, col: 1, offset: 6161},
			expr: &charClassMatcher{
				pos:        position{line: 345, col: 5, offset: 6171},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Field",
			pos:  position{line: 347, col: 1, offset: 6178},
			expr: &actionExpr{
				pos: position{line: 348, col: 5, offset: 6188},
				run: (*parser).callonField1,
				expr: &labeledExpr{
					pos:   position{line: 348, col: 5, offset: 6188},
					label: "field",
					expr: &litMatcher{
						pos:        position{line: 348, col: 11, offset: 6194},
						val:        "$",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name:        "RegularExpressionLiteral",
			displayName: "\"regular expression\"",
			pos:         position{line: 352, col: 1, offset: 6248},
			expr: &actionExpr{
				pos: position{line: 353, col: 5, offset: 6298},
				run: (*parser).callonRegularExpressionLiteral1,
				expr: &seqExpr{
					pos: position{line: 353, col: 5, offset: 6298},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 353, col: 5, offset: 6298},
							val:        "/",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 353, col: 9, offset: 6302},
							label: "pattern",
							expr: &ruleRefExpr{
								pos:  position{line: 353, col: 17, offset: 6310},
								name: "RegularExpressionBody",
							},
						},
						&litMatcher{
							pos:        position{line: 353, col: 39, offset: 6332},
							val:        "/",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "RegularExpressionBody",
			pos:  position{line: 357, col: 1, offset: 6374},
			expr: &actionExpr{
				pos: position{line: 358, col: 5, offset: 6400},
				run: (*parser).callonRegularExpressionBody1,
				expr: &labeledExpr{
					pos:   position{line: 358, col: 5, offset: 6400},
					label: "chars",
					expr: &oneOrMoreExpr{
						pos: position{line: 358, col: 11, offset: 6406},
						expr: &ruleRefExpr{
							pos:  position{line: 358, col: 11, offset: 6406},
							name: "RegularExpressionChar",
						},
					},
				},
			},
		},
		{
			name: "RegularExpressionChar",
			pos:  position{line: 362, col: 1, offset: 6484},
			expr: &choiceExpr{
				pos: position{line: 363, col: 5, offset: 6510},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 363, col: 5, offset: 6510},
						run: (*parser).callonRegularExpressionChar2,
						expr: &seqExpr{
							pos: position{line: 363, col: 5, offset: 6510},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 363, col: 5, offset: 6510},
									expr: &charClassMatcher{
										pos:        position{line: 363, col: 6, offset: 6511},
										val:        "[\\\\/]",
										chars:      []rune{'\\', '/'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&labeledExpr{
									pos:   position{line: 363, col: 12, offset: 6517},
									label: "re",
									expr: &ruleRefExpr{
										pos:  position{line: 363, col: 15, offset: 6520},
										name: "RegularExpressionNonTerminator",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 366, col: 5, offset: 6582},
						name: "RegularExpressionBackslashSequence",
					},
				},
			},
		},
		{
			name: "RegularExpressionBackslashSequence",
			pos:  position{line: 368, col: 1, offset: 6618},
			expr: &choiceExpr{
				pos: position{line: 369, col: 5, offset: 6657},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 369, col: 5, offset: 6657},
						run: (*parser).callonRegularExpressionBackslashSequence2,
						expr: &litMatcher{
							pos:        position{line: 369, col: 5, offset: 6657},
							val:        "\\/",
							ignoreCase: false,
						},
					},
					&seqExpr{
						pos: position{line: 372, col: 5, offset: 6695},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 372, col: 5, offset: 6695},
								val:        "\\",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 372, col: 10, offset: 6700},
								name: "RegularExpressionNonTerminator",
							},
						},
					},
				},
			},
		},
		{
			name: "RegularExpressionNonTerminator",
			pos:  position{line: 374, col: 1, offset: 6732},
			expr: &actionExpr{
				pos: position{line: 375, col: 5, offset: 6767},
				run: (*parser).callonRegularExpressionNonTerminator1,
				expr: &seqExpr{
					pos: position{line: 375, col: 5, offset: 6767},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 375, col: 5, offset: 6767},
							expr: &ruleRefExpr{
								pos:  position{line: 375, col: 6, offset: 6768},
								name: "LineTerminator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 375, col: 21, offset: 6783},
							name: "SourceChar",
						},
					},
				},
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 379, col: 1, offset: 6834},
			expr: &anyMatcher{
				line: 380, col: 5, offset: 6849,
			},
		},
		{
			name: "__",
			pos:  position{line: 382, col: 1, offset: 6852},
			expr: &zeroOrMoreExpr{
				pos: position{line: 383, col: 5, offset: 6859},
				expr: &choiceExpr{
					pos: position{line: 383, col: 7, offset: 6861},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 383, col: 7, offset: 6861},
							name: "ws",
						},
						&ruleRefExpr{
							pos:  position{line: 383, col: 12, offset: 6866},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "ws",
			pos:  position{line: 385, col: 1, offset: 6874},
			expr: &charClassMatcher{
				pos:        position{line: 386, col: 5, offset: 6881},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "LineTerminator",
			pos:  position{line: 388, col: 1, offset: 6892},
			expr: &charClassMatcher{
				pos:        position{line: 389, col: 5, offset: 6911},
				val:        "[\\n\\r]",
				chars:      []rune{'\n', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 391, col: 1, offset: 6919},
			expr: &litMatcher{
				pos:        position{line: 392, col: 5, offset: 6927},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 394, col: 1, offset: 6933},
			expr: &notExpr{
				pos: position{line: 395, col: 5, offset: 6941},
				expr: &anyMatcher{
					line: 395, col: 6, offset: 6942,
				},
			},
		},
	},
}

func (c *current) onStart1(program interface{}) (interface{}, error) {
	return program, nil

}

func (p *parser) callonStart1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStart1(stack["program"])
}

func (c *current) onProgram1(body interface{}) (interface{}, error) {
	return program(body, c.text, c.pos)

}

func (p *parser) callonProgram1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProgram1(stack["body"])
}

func (c *current) onSourceElements1(head, tail interface{}) (interface{}, error) {
	return srcElems(head, tail)

}

func (p *parser) callonSourceElements1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSourceElements1(stack["head"], stack["tail"])
}

func (c *current) onVariableStatement1(declaration interface{}) (interface{}, error) {
	return varstmt(declaration, c.text, c.pos)

}

func (p *parser) callonVariableStatement1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariableStatement1(stack["declaration"])
}

func (c *current) onVariableDeclaration1(id, initExpr interface{}) (interface{}, error) {
	return vardecl(id, initExpr, c.text, c.pos)

}

func (p *parser) callonVariableDeclaration1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariableDeclaration1(stack["id"], stack["initExpr"])
}

func (c *current) onInitializer1(expression interface{}) (interface{}, error) {
	return expression, nil

}

func (p *parser) callonInitializer1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInitializer1(stack["expression"])
}

func (c *current) onExpressionStatement1(call interface{}) (interface{}, error) {
	return exprstmt(call, c.text, c.pos)

}

func (p *parser) callonExpressionStatement1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionStatement1(stack["call"])
}

func (c *current) onMemberExpression7(property interface{}) (interface{}, error) {
	return property, nil

}

func (p *parser) callonMemberExpression7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMemberExpression7(stack["property"])
}

func (c *current) onMemberExpression1(head, tail interface{}) (interface{}, error) {
	return memberexprs(head, tail, c.text, c.pos)

}

func (p *parser) callonMemberExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMemberExpression1(stack["head"], stack["tail"])
}

func (c *current) onCallExpression4(callee, args interface{}) (interface{}, error) {
	return callexpr(callee, args, c.text, c.pos)

}

func (p *parser) callonCallExpression4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallExpression4(stack["callee"], stack["args"])
}

func (c *current) onCallExpression14(args interface{}) (interface{}, error) {
	return callexpr(nil, args, c.text, c.pos)

}

func (p *parser) callonCallExpression14() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallExpression14(stack["args"])
}

func (c *current) onCallExpression19(property interface{}) (interface{}, error) {
	return memberexpr(nil, property, c.text, c.pos)

}

func (p *parser) callonCallExpression19() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallExpression19(stack["property"])
}

func (c *current) onCallExpression1(head, tail interface{}) (interface{}, error) {
	return callexprs(head, tail, c.text, c.pos)

}

func (p *parser) callonCallExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallExpression1(stack["head"], stack["tail"])
}

func (c *current) onArguments1(args interface{}) (interface{}, error) {
	return args, nil

}

func (p *parser) callonArguments1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArguments1(stack["args"])
}

func (c *current) onFunctionArgs1(first, rest interface{}) (interface{}, error) {
	return object(first, rest, c.text, c.pos)

}

func (p *parser) callonFunctionArgs1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgs1(stack["first"], stack["rest"])
}

func (c *current) onFunctionArgsRest1(arg interface{}) (interface{}, error) {
	return arg, nil

}

func (p *parser) callonFunctionArgsRest1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgsRest1(stack["arg"])
}

func (c *current) onFunctionArg1(key, value interface{}) (interface{}, error) {
	return property(key, value, c.text, c.pos)

}

func (p *parser) callonFunctionArg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArg1(stack["key"], stack["value"])
}

func (c *current) onLambdaExpression1(expr interface{}) (interface{}, error) {
	return function(expr), nil

}

func (p *parser) callonLambdaExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLambdaExpression1(stack["expr"])
}

func (c *current) onLogicalOperators1() (interface{}, error) {
	return logicalOp(c.text)

}

func (p *parser) callonLogicalOperators1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogicalOperators1()
}

func (c *current) onLogical1(head, tail interface{}) (interface{}, error) {
	return logicalExpression(head, tail, c.text, c.pos)

}

func (p *parser) callonLogical1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogical1(stack["head"], stack["tail"])
}

func (c *current) onEqualityOperators1() (interface{}, error) {
	return binaryOp(c.text)

}

func (p *parser) callonEqualityOperators1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualityOperators1()
}

func (c *current) onEquality1(head, tail interface{}) (interface{}, error) {
	return binaryExpression(head, tail, c.text, c.pos)

}

func (p *parser) callonEquality1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEquality1(stack["head"], stack["tail"])
}

func (c *current) onRelationalOperators1() (interface{}, error) {
	return binaryOp(c.text)

}

func (p *parser) callonRelationalOperators1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelationalOperators1()
}

func (c *current) onRelational1(head, tail interface{}) (interface{}, error) {
	return binaryExpression(head, tail, c.text, c.pos)

}

func (p *parser) callonRelational1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelational1(stack["head"], stack["tail"])
}

func (c *current) onAdditiveOperator1() (interface{}, error) {
	return binaryOp(c.text)

}

func (p *parser) callonAdditiveOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditiveOperator1()
}

func (c *current) onAdditive1(head, tail interface{}) (interface{}, error) {
	return binaryExpression(head, tail, c.text, c.pos)

}

func (p *parser) callonAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1(stack["head"], stack["tail"])
}

func (c *current) onMultiplicativeOperator1() (interface{}, error) {
	return binaryOp(c.text)

}

func (p *parser) callonMultiplicativeOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicativeOperator1()
}

func (c *current) onMultiplicative1(head, tail interface{}) (interface{}, error) {
	return binaryExpression(head, tail, c.text, c.pos)

}

func (p *parser) callonMultiplicative1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1(stack["head"], stack["tail"])
}

func (c *current) onPrimary2(expr interface{}) (interface{}, error) {
	return expr, nil

}

func (p *parser) callonPrimary2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimary2(stack["expr"])
}

func (c *current) onArray1(elements interface{}) (interface{}, error) {
	return elements, nil

}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["elements"])
}

func (c *current) onArrayElements1(first, rest interface{}) (interface{}, error) {
	return array(first, rest, c.text, c.pos), nil

}

func (p *parser) callonArrayElements1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArrayElements1(stack["first"], stack["rest"])
}

func (c *current) onArrayRest1(element interface{}) (interface{}, error) {
	return element, nil

}

func (p *parser) callonArrayRest1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArrayRest1(stack["element"])
}

func (c *current) onDateTime1() (interface{}, error) {
	return datetime(c.text, c.pos)

}

func (p *parser) callonDateTime1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDateTime1()
}

func (c *current) onDuration1() (interface{}, error) {
	return durationLiteral(c.text, c.pos)

}

func (p *parser) callonDuration1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDuration1()
}

func (c *current) onStringLiteral2() (interface{}, error) {
	return stringLiteral(c.text, c.pos)

}

func (p *parser) callonStringLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral2()
}

func (c *current) onStringLiteral8() (interface{}, error) {
	return "", errors.New("string literal not terminated")

}

func (p *parser) callonStringLiteral8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral8()
}

func (c *current) onDoubleStringEscape3() (interface{}, error) {
	return nil, errors.New("invalid escape character")

}

func (p *parser) callonDoubleStringEscape3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleStringEscape3()
}

func (c *current) onBooleanLiteral2() (interface{}, error) {
	return booleanLiteral(true, c.text, c.pos)

}

func (p *parser) callonBooleanLiteral2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooleanLiteral2()
}

func (c *current) onBooleanLiteral7() (interface{}, error) {
	return booleanLiteral(false, c.text, c.pos)

}

func (p *parser) callonBooleanLiteral7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooleanLiteral7()
}

func (c *current) onIdentifier1() (interface{}, error) {
	return identifier(c.text, c.pos)

}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onNumber1() (interface{}, error) {
	return numberLiteral(c.text, c.pos)

}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onInteger1() (interface{}, error) {
	return integerLiteral(c.text, c.pos)

}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onField1(field interface{}) (interface{}, error) {
	return fieldLiteral(c.text, c.pos)

}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["field"])
}

func (c *current) onRegularExpressionLiteral1(pattern interface{}) (interface{}, error) {
	return pattern, nil

}

func (p *parser) callonRegularExpressionLiteral1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegularExpressionLiteral1(stack["pattern"])
}

func (c *current) onRegularExpressionBody1(chars interface{}) (interface{}, error) {
	return regexLiteral(chars, c.text, c.pos)

}

func (p *parser) callonRegularExpressionBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegularExpressionBody1(stack["chars"])
}

func (c *current) onRegularExpressionChar2(re interface{}) (interface{}, error) {
	return re, nil

}

func (p *parser) callonRegularExpressionChar2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegularExpressionChar2(stack["re"])
}

func (c *current) onRegularExpressionBackslashSequence2() (interface{}, error) {
	return "/", nil

}

func (p *parser) callonRegularExpressionBackslashSequence2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegularExpressionBackslashSequence2()
}

func (c *current) onRegularExpressionNonTerminator1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonRegularExpressionNonTerminator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegularExpressionNonTerminator1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// the globalStore allows the parser to store arbitrary values
	globalStore map[string]interface{}
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(map[string]interface{}),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n == 1 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		p.failAt(true, start.position, ".")
		return p.sliceFrom(start), true
	}
	p.failAt(false, p.pt.position, ".")
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError {
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
